Fixed delbyname, clear. Added oneliner.

diff --git a/slurmtk b/slurmtk
--- a/slurmtk
+++ b/slurmtk
@@ -56,7 +56,7 @@ LONGOPTS=help
 if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
     # e.g. return value is 1
     #  then getopt has complained about wrong arguments to stdout
-    exit 2
+    exit 102
 fi
 
 eval set -- "$PARSED"
@@ -77,7 +77,7 @@ while true; do
             ;;
         *)
             echo "Programming error"
-            exit 3
+            exit 101
             ;;
     esac
 done
@@ -116,21 +116,59 @@ then
 elif [ $1 == 'clear' ]
 then
     #   Search the queue for job IDs made by $USER. Feeds them into scancel
-    squeue -u $USER -h -o "%i" | xargs scancel
+    echo "Canceling jobs:" > /dev/stderr
+    squeue -u $USER -h -o "%i %j" \
+        | tee /dev/stderr \
+        | awk '{print $1}' \
+        | xargs scancel
 
 elif [ $1 == 'delbyname' ]
 then
     #   Check if there is a $2. If not, spit an error.
-    if [ ! $2 ]
+    if [ -z "$2" ]
     then
         echo "Error: no regex given in \$2. See help text below for usage."
         echo $helpstring
         exit 3
     fi
 
-    #   Search the queue for job IDs made by $USER.
-    #   Check jobs against the Perl regex in $2, then feed them into scancel
-    squeue -u $USER -h -o "%j" | perl -n -e 'print if m/$2/' | xargs scancel
+    #   Search the queue for job names and IDs made by $USER.
+    #   Check job names/IDs against the Perl regex in $2
+    #   Feed matches' IDs into scancel
+    echo "Canceling jobs:" > /dev/stderr
+    squeue -u $USER -h -o "%i %j" \
+        | perl -n -e 'print if m/$2/' \
+        | tee /dev/stderr \
+        | awk '{print $1}' \
+        | xargs scancel
+
+elif [ $1 == 'oneliner' ]
+then
+    #   Check if there's a command to pass and there's nothing else
+    if [ -z "$2" ]
+    then
+        echo "Error: No command passed to oneliner script."
+        echo $helpstring
+        exit 3
+    elif [ -n "$3" ]
+    then
+        echo "Error: either the command you want to pass to the scheduler is"
+        echo "not in double quotes, or more than one command was passed."
+        exit 4
+    fi
+
+    #   Find oneliner script. If it's there, execute it.
+    olscr="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/lib/oneliner
+    if [ -f $olscr ]
+    then
+#        echo "$olscr \"${@:2}\""
+        $olscr "$2"
+    else
+        echo "Error: oneliner script not found at $olscr."
+        echo "Please attempt to reinstall the latest version from Github."
+        echo "If error persists, please contact the devs."
+    fi
+
 
 elif [ $1 == 'watch' ]
 then
@@ -150,3 +188,17 @@ else
     echo $helpstring
     exit 2
 fi
+
+################################################################################
+#                                                                              #
+#   Error codes
+#
+#   1   No primary command in $1
+#   2   Unrecognised primary command in $1
+#   3   Missing value in $2
+#   4   
+#   100 Version of getopt in environment not compatible with this script
+#   101 I don't know what this does, but there's an exit status associated
+#   102 Unrecognised arguments in the getopt section
+#                                                                              #
+################################################################################
